#       Type here your functions & practice Python. :)
#       I HAVE TO PASTE OVER INFORMATION ABOUT THE EXERCISES HERE IM NOT THERE YET I STILL HAVE LOTS OF EXERCISES TO DO
#       BE PATIENT MY FELLOW HOMIES